### ISSUE TITLE
AttributeError: 'XGBModel' object has no attribute 'kwargs'

### ISSUE THREAD

**Issue by MuppalaSunnyChowdhary** [aadilkhalifa/crop-prediction#1]
When i was trying to run the application I'm getting AttributeError: 'XGBModel' object has no attribute 'kwargs'. as the kwargs is defined its showing the same error can you please help me out with the error

**Comment by aadilkhalifa** [comment]
This is because you're using a newer version of xgboost. 

This should help. 
[https://stackoverflow.com/questions/56755507/opening-old-xgboost-pickles-with-the-new-xgboost-version-xgbclassifier-object](url)
